"""followers

Revision ID: 8625a5d369a5
Revises: b73b47483932
Create Date: 2018-02-02 12:47:44.945007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8625a5d369a5'
down_revision = 'b73b47483932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
